# Generated by Django 4.2 on 2023-04-18 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todoitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="todos.todolist",
            ),
            preserve_default=False,
        ),
    ]
